# Class for reading and saving the game configuration

class Config(object):
    def __init__(self):
        """All default settings go here."""
        self.screen_height = 480
        self.screen_width = 640
        self.music = 1
        self.fps_counter = 1

    def save_settings(self):
        """Saves current settings to the file to be read on start: settings.py"""
        f = open("settings.py", "w")
        f.write("# Generated by the game, your changes may be overwritten if you edit while running\n\n")
        f.write("import config\n")
        f.write("c = config.Config()\n\n")

        for k, v in self.__dict__.iteritems():
            if not (k.startswith('__') or (type(v) == str and v[0].startswith('<'))):
                f.write("c." + k + " = " + str(v) + "\n")

        f.close()
